package com.iwaa.client.local;

public enum Constants {

    MISTAKE_CONNECTION("mistake_connection"),
    HOST("host"),
    PORT("port"),
    CONNECT_BUTTON("connect_button"),
    CONNECT_WINDOW("connect_window"),
    MISTAKE_USER("mistake_user"),
    MISTAKE_LOGIN("mistake_login"),
    SIGN_IN_BUTTON("sign_in_button"),
    SIGN_UP_BUTTON("sign_up_button"),
    LOGIN("login"),
    PASSWORD("password"),
    INFO("info"),
    LOGIN_WINDOW("login_window"),
    SORT_BUTTON("sort_button"),
    FILTER_BUTTON("filter_button"),
    SORT_MISTAKE("sort_mistake"),
    MAIN_WINDOW("main_window"),
    LOGIN_INFO("login_info"),
    INFO_WINDOW("info_window"),
    PRINTER_WINDOW("printer_window"),
    PRINTER_INFO("printer_info"),
    GROUP_WINDOW("group_window"),
    HISTORY_WINDOW("history_window"),
    HELP_WINDOW("help_window"),
    VIEW_WINDOW("view_window"),
    AUTHOR("author"),
    IDENTIFICATION("identification"),
    NAME("name"),
    COORDINATES("coordinates"),
    CREATION_DATE("creation_date"),
    LOCATION_TO("location_to"),
    LOCATION_FROM("location_from"),
    DISTANCE("distance"),
    ASCENDING("ascending"),
    DESCENDING("descending"),
    SORT_WINDOW("sort_window"),
    NUMBER("number"),
    NUMBER_INT("number_int"),
    NUMBER_LONG("number_long"),
    NUMBER_FLOAT("number_float"),
    STRING("string"),
    DATE("date"),
    DATE_FORMAT("date_format"),
    MISTAKE("mistake"),
    DESCRIPTION_ADD("description_add"),
    ADD_WINDOW("add_window"),
    ADD_BUTTON("add_button"),
    ADD_IF_MAX_BUTTON("add_if_max_button"),
    DISTANCE_ENTER("distance_enter"),
    MISTAKE_DISTANCE("mistake_distance"),
    FILTER_WINDOW("filter_window"),
    RESULT_FILTER("result_filter"),
    TITLE("title"),
    INSERT("insert"),
    NIT_MAX("not_max"),
    SUCCESS("success"),
    MISTAKE_DATA("mistake_data"),
    ENTER_LOCATION_TO("enter_location_to"),
    ENTER_LOCATION_FROM("enter_location_from"),
    X("x"),
    Y("y"),
    Z("z"),
    ENTER_COORDINATES("enter_coordinates"),
    COORDINATE_X("coordinate_x"),
    COORDINATE_Y("coordinate_y"),
    ENTER_DISTANCE("enter_distance"),
    ENTER_NAME("enter_name"),
    SEND("send"),
    LANGUAGE("language"),
    RUSSIAN("russian"),
    FRENCH("french"),
    NORWEGIAN("norwegian"),
    ENGLISH("english"),

    REMOVE_DESCRIPTION("remove_description"),
    REMOVE("remove"),
    REMOVE_BY_ID("remove_by_id"),
    REMOVE_INFO("remove_info"),
    MISTAKE_REMOVE_INFO("mistake_remove_info"),
    REMOVE_MISTAKE("remove_mistake"),
    SUCCESS_REMOVES("success_removed"),
    REMOVE_LOWER("remove_lower"),
    CLEAR("clear"),

    EXECUTE_SCRIPT_WINDOW("execute_script_window"),
    PATH("path"),
    EXECUTE("execute"),
    MISTAKE_PATH("mistake_path");


    private final String string;

    Constants(String string) {
        this.string = string;
    }

    public String getString() {
        return string;
    }
}
